### PR TITLE
Fix for Meteor v1.0

### PR DESCRIPTION
**Pull request by bstocks**
Hi @dfischer - I had to make these changes in order to successfully deploy to modulus while running meteor v1.0

### CODE REVIEW

**Comment by dfischer** [comment]
:+1: thanks.

**Comment by bstocks** [comment]
Sure thing. Thank you for the package! As soon as this fix hits atmosphere, I'll be adding it to about 8 production sites/apps that live on modulus.

**Comment by dfischer** [comment]
Glad I can start something helpful. :)

I noticed spiderable crashing a lot so I made this: https://github.com/dfischer/meteor-prerenderio

Let me know if you decide to use that instead. I'm having great success with it. It costs money but oh well.

**Comment by bstocks** [comment]
Interesting, I'll check that out. Thanks.

Question: I've never published a package to Atmosphere myself, how long should I expect it to take before these changes get up to the Atmosphere server?

**Comment by dfischer** [comment]
I already pushed the changes. If you check atmosphere it should reflect that. But maybe there needs to be a version bump? It's not updated yet? 

—Daniel Fischer

http://www.danielfischer.com

http://www.twitter.com/dfischer

http://www.github.com/dfischer

**Comment by bstocks** [comment]
Ah, right you are. Not sure what happened the first time, but it's working now. Thanks!

**Pull request merged**
